---
# tasks file for talos
- name: Stat talos config
  ansible.builtin.stat:
    path: "{{ talos_config_dir }}/controlplane.yaml"
  register: result

- name: Generate talos config
  ansible.builtin.command: >
    talosctl gen config
      {{ talos_cluster_name }}
      https://{{ talos_node_ip }}:{{ talos_kube_api_port }}
      --output-types controlplane,talosconfig
      --output-dir {{ talos_config_dir }}
  when: result.stat is defined and not result.stat.exists
  register: result
  changed_when: result.rc == 0
  failed_when: result.rc != 0

- name: Patch machine config with cilium values
  ansible.builtin.command: >
    talosctl machineconfig patch
    {{ talos_config_dir }}/controlplane.yaml
    --patch @{{ talos_config_dir }}/cilium.yaml
    -o {{ talos_config_dir }}/controlplane.patched.yaml
  changed_when: false
  tags:
    - talos_upgrade_cilium

- name: Patch machine config with talos values
  ansible.builtin.command: >
    yq --inplace '{{ talos_patches }}'
    {{ talos_config_dir }}/controlplane.patched.yaml
  changed_when: false
