---
- name: Create talos config temporary directory
  ansible.builtin.file:
    path: "{{ talos_config_dir }}"
    state: directory
    mode: "0750"

- name: Generate additional inline manifests for talos
  ansible.builtin.import_tasks: generate_inline_manifests_patch.yml
  tags:
    - talos_upgrade_inline_manifests

- name: Configure talos
  ansible.builtin.import_tasks: config_talos.yml

- name: Bootstrap talos machine
  ansible.builtin.import_tasks: bootstrap_talos.yml

- name: Configure workspace (kubectl|talosctl)
  ansible.builtin.import_tasks: config_workspace.yml

- name: Configure cilium post-install manifests
  ansible.builtin.import_tasks: config_cilium_manifests.yml
  tags:
    - talos_upgrade_inline_manifests
