---
- name: Converge
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Test Loadbalancer IP connectivity
      ansible.builtin.import_role:
        name: talos
        tasks_from: test_lb_connectivity.yml
