---
- name: Converge
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Fetch a list of Nodes
      ansible.builtin.debug:
        msg: "{{ query('kubernetes.core.k8s', api_version='v1', kind='Node') }}"
